//! Static screen: the app's own license + the third-party software notices (reached from
//! Settings).

use super::style::*;
use super::{AppCtx, Screen};
use std::sync::Arc;
use windows_reactor::*;

/// punktfunk's own license (MIT OR Apache-2.0).
const APP_LICENSE: &str = concat!(
    include_str!("../../../../LICENSE-MIT"),
    "\n\n================================ Apache-2.0 ================================\n\n",
    include_str!("../../../../LICENSE-APACHE"),
);
/// Third-party software notices for the Rust crates THIS CLIENT links — the shell, the
/// session streamer and the headless CLI (generated by scripts/gen-third-party-notices.sh;
/// the MSIX ships the same file under licenses/).
///
/// Deliberately the client-scoped file and not the workspace-wide one at the repo root:
/// that root file is the HOST's, it still carries `ffmpeg-next` and the full FFmpeg licence
/// text — and after M10 this app bundles no FFmpeg at all, so printing that attribution
/// three lines under a card saying so would be a false statement to the user's face.
const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

pub(crate) fn licenses_page(ctx: &Arc<AppCtx>, set_screen: &AsyncSetState<Screen>) -> Element {
    let back_btn = button("返回").accent().icon(Symbol::Back).on_click({
        let (c, ss) = (ctx.clone(), set_screen.clone());
        move || {
            // Back RE-ENTERS the settings page — re-base its snapshot on the file, same
            // as the hosts page's Settings button (see settings::refresh_snapshot).
            super::settings::refresh_snapshot(&c);
            ss.call(Screen::Settings)
        }
    });

    let app_card = card(
        vstack((
            text_block("Punktfunk").font_size(15.0).semibold(),
            text_block("按 MIT 或 Apache-2.0 许可授权，由你选择。")
                .font_size(12.0)
                .wrap()
                .foreground(ThemeRef::SecondaryText),
            text_block(APP_LICENSE)
                .font_size(11.0)
                .wrap()
                .foreground(ThemeRef::SecondaryText),
        ))
        .spacing(8.0),
    );

    let natives_card = card(
        vstack((
            text_block("捆绑组件").font_size(15.0).semibold(),
            text_block(
                "链接了 SDL 3（Zlib）和 Windows App SDK（Microsoft），其许可声明随\
                 安装目录下的 licenses\\ 文件夹提供。视频解码使用 Windows 自带的\
                 DXVA 和 Vulkan Video，CPU 回退为 OpenH264 和 rav1d（均为\
                 BSD-2-Clause）——未捆绑 FFmpeg。",
            )
            .font_size(12.0)
            .wrap()
            .foreground(ThemeRef::SecondaryText),
        ))
        .spacing(8.0),
    );

    let notices_card = card(
        vstack((
            text_block("Rust 组件").font_size(15.0).semibold(),
            text_block(THIRD_PARTY_NOTICES)
                .font_size(11.0)
                .wrap()
                .foreground(ThemeRef::SecondaryText),
        ))
        .spacing(8.0),
    );

    page(vec![
        page_header("第三方许可", back_btn),
        section("PUNKTFUNK"),
        app_card.into(),
        section("捆绑组件"),
        natives_card.into(),
        section("开源组件"),
        notices_card.into(),
    ])
}
